### ISSUE TITLE
Default username

### ISSUE THREAD

**Issue by PapaGuacamole** [trevize-achaea/scripts#1]
Hi Trevize,

Great script, thanks for sharing. However, I've a little niggle, it uses your character's name and not mine!

Change the first line of the script block from

local me = "Trevize"

to

local me = "Me"

I was going to suggest (and did before testing and editing) using gmcp.Char.Status.name, but that causes the code block to error when there is no gmcp. It might be worth adding something into the code later on to update the variable with the gmcp name when it's available, eg in goldtracker.display():

if gmcp and me == "Me" then me = gmcp.Char.Status.name end

**Comment by trevize-achaea** [comment]
There is no website with instructions yet, but the gold tracker is intended to be modified at the top of the script to use your character name (among other settings). It uses GMCP for resets after that, but that's not usable upon initialization, as you noticed, as GMCP is not available yet.

Using 'Me' is not supportable due to the 'report' trigger for party chats - it would read awkward. Updates to cover changing me to the character name would have to be littered throughout the script.

An update is planned to solve this, but for now, modify the name at the top of the script.
